FROM quay.io/maherzubair/sigma-md:beta
RUN git clone https://github.com/Nexxer777/NEXXER-MD /root/Maher-Zubair/NEXXER-MD
WORKDIR /root/Maher-Nexxer777/NEXXER-MD/
RUN npm install npm@latest
RUN npm install
EXPOSE 8000
CMD ["npm", "start"]
 
 
